//! @file     D3D11Methods.h
//! @author   LiCode
//! @version  1.1
//! @date     2007.10
//! Copyright ...

#ifndef DEFINE_FUNC_PTR
#define DEFINE_FUNC_PTR( Ret, FuncName, Args ) Ret FuncName Args;
#endif

// DXGI
DEFINE_FUNC_PTR( 
	HRESULT, 
	CreateDXGIFactory1, 
	(REFIID, _void**) 
	)

// D3D11
DEFINE_FUNC_PTR( 
	HRESULT, 
	D3D11CreateDevice,
	(IDXGIAdapter*, D3D_DRIVER_TYPE, HMODULE, UINT, CONST D3D_FEATURE_LEVEL*, UINT, UINT, ID3D11Device**, D3D_FEATURE_LEVEL*, ID3D11DeviceContext**)
	)
DEFINE_FUNC_PTR( 
	HRESULT, 
	D3D11CreateDeviceAndSwapChain, 
	(IDXGIAdapter*, D3D_DRIVER_TYPE, HMODULE, UINT, CONST D3D_FEATURE_LEVEL*, UINT, UINT, DXGI_SWAP_CHAIN_DESC*, IDXGISwapChain**, ID3D11Device**, D3D_FEATURE_LEVEL*, ID3D11DeviceContext**) 
	)

// D3DHLSL
DEFINE_FUNC_PTR( 
	HRESULT, 
	D3DCompile, 
	(LPCVOID, SIZE_T, LPCSTR, CONST D3D_SHADER_MACRO*, LPD3DINCLUDE, LPCSTR, LPCSTR, UINT, UINT, LPD3DBLOB*, LPD3DBLOB*) 
	)
DEFINE_FUNC_PTR( 
	HRESULT, 
	D3DPreprocess, 
	(LPCVOID, SIZE_T, LPCSTR, CONST D3D10_SHADER_MACRO*, LPD3D10INCLUDE, LPD3D10BLOB*, LPD3D10BLOB*)
	)
DEFINE_FUNC_PTR( 
	HRESULT, 
	D3DGetDebugInfo, 
	(LPCVOID, SIZE_T, LPD3DBLOB*) 
	)
DEFINE_FUNC_PTR( 
	HRESULT, 
	D3DReflect, 
	(LPCVOID, SIZE_T, REFIID, void**) 
	)
DEFINE_FUNC_PTR( 
	HRESULT, 
	D3DDisassemble, 
	(LPCVOID, SIZE_T, UINT, LPCSTR, LPD3DBLOB*) 
	)

// D3DX11
DEFINE_FUNC_PTR( 
	HRESULT, 
	D3DX11CreateTextureFromMemory, 
	(ID3D11Device*, LPCVOID, SIZE_T, D3DX11_IMAGE_LOAD_INFO*, ID3DX11ThreadPump*, ID3D11Resource**, HRESULT*) 
	)
DEFINE_FUNC_PTR( 
	HRESULT, 
	D3DX11GetImageInfoFromMemory, 
	(LPCVOID, SIZE_T, ID3DX11ThreadPump*, D3DX11_IMAGE_INFO*, HRESULT*) 
	)
DEFINE_FUNC_PTR( 
	HRESULT, 
	D3DX11SaveTextureToMemory, 
	(ID3D11DeviceContext*, ID3D11Resource*, D3DX11_IMAGE_FILE_FORMAT, ID3D10Blob**, UINT) 
	)
DEFINE_FUNC_PTR( 
	HRESULT, 
	D3DX11SaveTextureToFileW, 
	(ID3D11DeviceContext*, ID3D11Resource*, D3DX11_IMAGE_FILE_FORMAT, LPCWSTR) 
	)
DEFINE_FUNC_PTR( 
	HRESULT, 
	D3DX11LoadTextureFromTexture, 
	(ID3D11DeviceContext*, ID3D11Resource*, D3DX11_TEXTURE_LOAD_INFO*, ID3D11Resource*) 
	)