//! @file     GDIMethods.h
//! @author   LiCode
//! @version  1.1
//! @date     2007.10
//! Copyright ...

#ifndef DEFINE_FUNC_PTR
#define DEFINE_FUNC_PTR( Ret, FuncName, Args ) Ret FuncName Args;
#endif

DEFINE_FUNC_PTR( Gdiplus::Status, 	GdiplusStartup, (ULONG_PTR*, const Gdiplus::GdiplusStartupInput*, Gdiplus::GdiplusStartupOutput*) )
DEFINE_FUNC_PTR( VOID,				GdiplusShutdown, (ULONG_PTR) )

// ImageAttributes APIs
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateImageAttributes, (Gdiplus::GpImageAttributes**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCloneImageAttributes, (GDIPCONST Gdiplus::GpImageAttributes*, Gdiplus::GpImageAttributes**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDisposeImageAttributes, (Gdiplus::GpImageAttributes*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetImageAttributesToIdentity, (Gdiplus::GpImageAttributes*, Gdiplus::ColorAdjustType) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipResetImageAttributes, (Gdiplus::GpImageAttributes*, Gdiplus::ColorAdjustType) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetImageAttributesColorMatrix, (Gdiplus::GpImageAttributes*, Gdiplus::ColorAdjustType, BOOL, GDIPCONST Gdiplus::ColorMatrix*, GDIPCONST Gdiplus::ColorMatrix*, Gdiplus::ColorMatrixFlags) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetImageAttributesThreshold, (Gdiplus::GpImageAttributes*, Gdiplus::ColorAdjustType, BOOL, Gdiplus::REAL) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetImageAttributesGamma, (Gdiplus::GpImageAttributes*, Gdiplus::ColorAdjustType, BOOL, Gdiplus::REAL) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetImageAttributesNoOp, (Gdiplus::GpImageAttributes*, Gdiplus::ColorAdjustType, BOOL) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetImageAttributesColorKeys, (Gdiplus::GpImageAttributes*, Gdiplus::ColorAdjustType, BOOL, Gdiplus::ARGB, Gdiplus::ARGB) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetImageAttributesOutputChannel, (Gdiplus::GpImageAttributes*, Gdiplus::ColorAdjustType, BOOL, Gdiplus::ColorChannelFlags) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetImageAttributesOutputChannelColorProfile, (Gdiplus::GpImageAttributes*, Gdiplus::ColorAdjustType, BOOL, GDIPCONST WCHAR*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetImageAttributesRemapTable, (Gdiplus::GpImageAttributes*, Gdiplus::ColorAdjustType, BOOL, UINT, GDIPCONST Gdiplus::ColorMap*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetImageAttributesWrapMode, (Gdiplus::GpImageAttributes*, Gdiplus::WrapMode, Gdiplus::ARGB, BOOL) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetImageAttributesICMMode, (Gdiplus::GpImageAttributes*, BOOL) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetImageAttributesAdjustedPalette, (Gdiplus::GpImageAttributes*, Gdiplus::ColorPalette*, Gdiplus::ColorAdjustType) )

// Graphics APIs
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipFlush, (Gdiplus::GpGraphics*, Gdiplus::GpFlushIntention) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateFromHDC, (HDC, Gdiplus::GpGraphics**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateFromHDC2, (HDC, HANDLE, Gdiplus::GpGraphics**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateFromHWND, (HWND, Gdiplus::GpGraphics**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateFromHWNDICM, (HWND, Gdiplus::GpGraphics**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDeleteGraphics, (Gdiplus::GpGraphics*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetDC, (Gdiplus::GpGraphics*, HDC*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipReleaseDC, (Gdiplus::GpGraphics*, HDC) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetCompositingMode, (Gdiplus::GpGraphics*, Gdiplus::CompositingMode) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetCompositingMode, (Gdiplus::GpGraphics*, Gdiplus::CompositingMode*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetRenderingOrigin, (Gdiplus::GpGraphics*, INT, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetRenderingOrigin, (Gdiplus::GpGraphics*, INT*, INT*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetCompositingQuality, (Gdiplus::GpGraphics*, Gdiplus::CompositingQuality) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetCompositingQuality, (Gdiplus::GpGraphics*, Gdiplus::CompositingQuality*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetSmoothingMode, (Gdiplus::GpGraphics*, Gdiplus::SmoothingMode) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetSmoothingMode, (Gdiplus::GpGraphics*, Gdiplus::SmoothingMode*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetPixelOffsetMode, (Gdiplus::GpGraphics*, Gdiplus::PixelOffsetMode) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetPixelOffsetMode, (Gdiplus::GpGraphics*, Gdiplus::PixelOffsetMode*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetTextRenderingHint, (Gdiplus::GpGraphics*, Gdiplus::TextRenderingHint) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetTextRenderingHint, (Gdiplus::GpGraphics*, Gdiplus::TextRenderingHint*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetTextContrast, (Gdiplus::GpGraphics*, UINT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetTextContrast, (Gdiplus::GpGraphics*, UINT*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetInterpolationMode, (Gdiplus::GpGraphics*, Gdiplus::InterpolationMode) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetInterpolationMode, (Gdiplus::GpGraphics*, Gdiplus::InterpolationMode*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetWorldTransform, (Gdiplus::GpGraphics*, Gdiplus::GpMatrix*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipResetWorldTransform, (Gdiplus::GpGraphics*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipMultiplyWorldTransform, (Gdiplus::GpGraphics*, GDIPCONST Gdiplus::GpMatrix*, Gdiplus::GpMatrixOrder) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipTranslateWorldTransform, (Gdiplus::GpGraphics*, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::GpMatrixOrder) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipScaleWorldTransform, (Gdiplus::GpGraphics*, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::GpMatrixOrder) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipRotateWorldTransform, (Gdiplus::GpGraphics*, Gdiplus::REAL, Gdiplus::GpMatrixOrder) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetWorldTransform, (Gdiplus::GpGraphics*, Gdiplus::GpMatrix*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipResetPageTransform, (Gdiplus::GpGraphics*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetPageUnit, (Gdiplus::GpGraphics*, Gdiplus::GpUnit*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetPageScale, (Gdiplus::GpGraphics*, Gdiplus::REAL*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetPageUnit, (Gdiplus::GpGraphics*, Gdiplus::GpUnit) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetPageScale, (Gdiplus::GpGraphics*, Gdiplus::REAL) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetDpiX, (Gdiplus::GpGraphics*, Gdiplus::REAL*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetDpiY, (Gdiplus::GpGraphics*, Gdiplus::REAL*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipTransformPoints, (Gdiplus::GpGraphics*, Gdiplus::GpCoordinateSpace, Gdiplus::GpCoordinateSpace, Gdiplus::GpPointF*, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipTransformPointsI, (Gdiplus::GpGraphics*, Gdiplus::GpCoordinateSpace, Gdiplus::GpCoordinateSpace, Gdiplus::GpPoint*, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetNearestColor, (Gdiplus::GpGraphics*, Gdiplus::ARGB*) )

// Image APIs
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipLoadImageFromStream, (IStream*, Gdiplus::GpImage**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipLoadImageFromFile, (GDIPCONST WCHAR*, Gdiplus::GpImage**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipLoadImageFromStreamICM, (IStream*, Gdiplus::GpImage**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipLoadImageFromFileICM, (GDIPCONST WCHAR*, Gdiplus::GpImage**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCloneImage, (Gdiplus::GpImage*, Gdiplus::GpImage**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDisposeImage, (Gdiplus::GpImage*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSaveImageToFile, (Gdiplus::GpImage*, GDIPCONST WCHAR*, GDIPCONST CLSID*, GDIPCONST Gdiplus::EncoderParameters*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSaveImageToStream, (Gdiplus::GpImage*, IStream*, GDIPCONST CLSID*, GDIPCONST Gdiplus::EncoderParameters*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSaveAdd, (Gdiplus::GpImage*, GDIPCONST Gdiplus::EncoderParameters*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSaveAddImage, (Gdiplus::GpImage*, Gdiplus::GpImage*, GDIPCONST Gdiplus::EncoderParameters*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetImageGraphicsContext, (Gdiplus::GpImage*, Gdiplus::GpGraphics**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetImageBounds, (Gdiplus::GpImage*, Gdiplus::GpRectF*, Gdiplus::GpUnit*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetImageDimension, (Gdiplus::GpImage*, Gdiplus::REAL*, Gdiplus::REAL*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetImageType, (Gdiplus::GpImage*, Gdiplus::ImageType*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetImageWidth, (Gdiplus::GpImage*, UINT*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetImageHeight, (Gdiplus::GpImage*, UINT*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetImageHorizontalResolution, (Gdiplus::GpImage*, Gdiplus::REAL*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetImageVerticalResolution, (Gdiplus::GpImage*, Gdiplus::REAL*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetImageFlags, (Gdiplus::GpImage*, UINT*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetImageRawFormat, (Gdiplus::GpImage*, GUID*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetImagePixelFormat, (Gdiplus::GpImage*, Gdiplus::PixelFormat*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetImageThumbnail, (Gdiplus::GpImage*, UINT, UINT, Gdiplus::GpImage**, Gdiplus::GetThumbnailImageAbort, VOID*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetEncoderParameterListSize, (Gdiplus::GpImage*, GDIPCONST CLSID*, UINT*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetEncoderParameterList, (Gdiplus::GpImage*, GDIPCONST CLSID*, UINT, Gdiplus::EncoderParameters*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipImageGetFrameDimensionsCount, (Gdiplus::GpImage*, UINT*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipImageGetFrameDimensionsList, (Gdiplus::GpImage*, GUID*, UINT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipImageGetFrameCount, (Gdiplus::GpImage*, GDIPCONST GUID*, UINT*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipImageSelectActiveFrame, (Gdiplus::GpImage*, GDIPCONST GUID*, UINT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipImageRotateFlip, (Gdiplus::GpImage*, Gdiplus::RotateFlipType) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetImagePalette, (Gdiplus::GpImage*, Gdiplus::ColorPalette*, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetImagePalette, (Gdiplus::GpImage*, GDIPCONST Gdiplus::ColorPalette*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetImagePaletteSize, (Gdiplus::GpImage*, INT*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetPropertyCount, (Gdiplus::GpImage*, UINT*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetPropertyIdList, (Gdiplus::GpImage*, UINT, PROPID*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetPropertyItemSize, (Gdiplus::GpImage*, PROPID, UINT*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetPropertyItem, (Gdiplus::GpImage*, PROPID, UINT, Gdiplus::PropertyItem*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetPropertySize, (Gdiplus::GpImage*, UINT*, UINT*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetAllPropertyItems, (Gdiplus::GpImage*, UINT, UINT, Gdiplus::PropertyItem*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipRemovePropertyItem, (Gdiplus::GpImage*, PROPID) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetPropertyItem, (Gdiplus::GpImage*, GDIPCONST Gdiplus::PropertyItem*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipImageForceValidation, (Gdiplus::GpImage*) )

// Bitmap APIs
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateBitmapFromStream, (IStream*, Gdiplus::GpBitmap**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateBitmapFromFile, (GDIPCONST WCHAR*, Gdiplus::GpBitmap**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateBitmapFromStreamICM, (IStream*, Gdiplus::GpBitmap**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateBitmapFromFileICM, (GDIPCONST WCHAR*, Gdiplus::GpBitmap**) )
// http://www.jose.it-berater.org/gdiplus/reference/flatapi/bitmap/gdipcreatebitmapfromscan0.htm
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateBitmapFromScan0, (INT, INT, INT, Gdiplus::PixelFormat, BYTE*, Gdiplus::GpBitmap**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateBitmapFromGraphics, (INT, INT, Gdiplus::GpGraphics*, Gdiplus::GpBitmap**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateBitmapFromDirectDrawSurface, (IDirectDrawSurface7*, Gdiplus::GpBitmap**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateBitmapFromGdiDib, (GDIPCONST BITMAPINFO*, VOID*, Gdiplus::GpBitmap**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateBitmapFromHBITMAP, (HBITMAP, HPALETTE, Gdiplus::GpBitmap**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateHBITMAPFromBitmap, (Gdiplus::GpBitmap*, HBITMAP*, Gdiplus::ARGB) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateBitmapFromHICON, (HICON, Gdiplus::GpBitmap**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateHICONFromBitmap, (Gdiplus::GpBitmap*, HICON*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateBitmapFromResource, (HINSTANCE, GDIPCONST WCHAR*, Gdiplus::GpBitmap**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCloneBitmapArea, (Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::PixelFormat, Gdiplus::GpBitmap*, Gdiplus::GpBitmap**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCloneBitmapAreaI, (INT, INT, INT, INT, Gdiplus::PixelFormat, Gdiplus::GpBitmap*, Gdiplus::GpBitmap**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipBitmapLockBits, (Gdiplus::GpBitmap*, GDIPCONST Gdiplus::GpRect*, UINT, Gdiplus::PixelFormat, Gdiplus::BitmapData*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipBitmapUnlockBits, (Gdiplus::GpBitmap*, Gdiplus::BitmapData*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipBitmapGetPixel, (Gdiplus::GpBitmap*, INT, INT, Gdiplus::ARGB*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipBitmapSetPixel, (Gdiplus::GpBitmap*, INT, INT, Gdiplus::ARGB) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipBitmapSetResolution, (Gdiplus::GpBitmap*, Gdiplus::REAL, Gdiplus::REAL) )

// Brush APIs
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCloneBrush, (Gdiplus::GpBrush*, Gdiplus::GpBrush**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDeleteBrush, (Gdiplus::GpBrush*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetBrushType, (Gdiplus::GpBrush*, Gdiplus::GpBrushType*) )

// HatchBrush APIs
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateHatchBrush, (Gdiplus::GpHatchStyle, Gdiplus::ARGB, Gdiplus::ARGB, Gdiplus::GpHatch**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetHatchStyle, (Gdiplus::GpHatch*, Gdiplus::GpHatchStyle*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetHatchForegroundColor, (Gdiplus::GpHatch*, Gdiplus::ARGB*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetHatchBackgroundColor, (Gdiplus::GpHatch*, Gdiplus::ARGB*) )

// TextureBrush APIs
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateTexture, (Gdiplus::GpImage*, Gdiplus::GpWrapMode, Gdiplus::GpTexture**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateTexture2, (Gdiplus::GpImage*, Gdiplus::GpWrapMode, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::GpTexture**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateTextureIA, (Gdiplus::GpImage*, GDIPCONST Gdiplus::GpImageAttributes*, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::GpTexture**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateTexture2I, (Gdiplus::GpImage*, Gdiplus::GpWrapMode, INT, INT, INT, INT, Gdiplus::GpTexture**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateTextureIAI, (Gdiplus::GpImage*, GDIPCONST Gdiplus::GpImageAttributes*, INT, INT, INT, INT, Gdiplus::GpTexture**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetTextureTransform, (Gdiplus::GpTexture*, Gdiplus::GpMatrix*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetTextureTransform, (Gdiplus::GpTexture*, GDIPCONST Gdiplus::GpMatrix*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipResetTextureTransform, (Gdiplus::GpTexture*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipMultiplyTextureTransform, (Gdiplus::GpTexture*, GDIPCONST Gdiplus::GpMatrix*, Gdiplus::GpMatrixOrder) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipTranslateTextureTransform, (Gdiplus::GpTexture*, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::GpMatrixOrder) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipScaleTextureTransform, (Gdiplus::GpTexture*, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::GpMatrixOrder) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipRotateTextureTransform, (Gdiplus::GpTexture*, Gdiplus::REAL, Gdiplus::GpMatrixOrder) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetTextureWrapMode, (Gdiplus::GpTexture*, Gdiplus::GpWrapMode) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetTextureWrapMode, (Gdiplus::GpTexture*, Gdiplus::GpWrapMode*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetTextureImage, (Gdiplus::GpTexture*, Gdiplus::GpImage**) )

// SolidBrush APIs
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateSolidFill, (Gdiplus::ARGB, Gdiplus::GpSolidFill**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetSolidFillColor, (Gdiplus::GpSolidFill*, Gdiplus::ARGB) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetSolidFillColor, (Gdiplus::GpSolidFill*, Gdiplus::ARGB*) )

// Pen APIs
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreatePen1, (Gdiplus::ARGB, Gdiplus::REAL, Gdiplus::GpUnit, Gdiplus::GpPen**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreatePen2, (Gdiplus::GpBrush*, Gdiplus::REAL, Gdiplus::GpUnit, Gdiplus::GpPen**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipClonePen, (Gdiplus::GpPen*, Gdiplus::GpPen**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDeletePen, (Gdiplus::GpPen*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetPenWidth, (Gdiplus::GpPen*, Gdiplus::REAL) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetPenWidth, (Gdiplus::GpPen*, Gdiplus::REAL*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetPenUnit, (Gdiplus::GpPen*, Gdiplus::GpUnit) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetPenUnit, (Gdiplus::GpPen*, Gdiplus::GpUnit*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetPenLineCap197819, (Gdiplus::GpPen*, Gdiplus::GpLineCap, Gdiplus::GpLineCap, Gdiplus::GpDashCap) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetPenStartCap, (Gdiplus::GpPen*, Gdiplus::GpLineCap) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetPenEndCap, (Gdiplus::GpPen*, Gdiplus::GpLineCap) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetPenDashCap197819, (Gdiplus::GpPen*, Gdiplus::GpDashCap) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetPenStartCap, (Gdiplus::GpPen*, Gdiplus::GpLineCap*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetPenEndCap, (Gdiplus::GpPen*, Gdiplus::GpLineCap*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetPenDashCap197819, (Gdiplus::GpPen*, Gdiplus::GpDashCap*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetPenLineJoin, (Gdiplus::GpPen*, Gdiplus::GpLineJoin) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetPenLineJoin, (Gdiplus::GpPen*, Gdiplus::GpLineJoin*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetPenCustomStartCap, (Gdiplus::GpPen*, Gdiplus::GpCustomLineCap*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetPenCustomStartCap, (Gdiplus::GpPen*, Gdiplus::GpCustomLineCap**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetPenCustomEndCap, (Gdiplus::GpPen*, Gdiplus::GpCustomLineCap*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetPenCustomEndCap, (Gdiplus::GpPen*, Gdiplus::GpCustomLineCap**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetPenMiterLimit, (Gdiplus::GpPen*, Gdiplus::REAL) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetPenMiterLimit, (Gdiplus::GpPen*, Gdiplus::REAL*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetPenMode, (Gdiplus::GpPen*, Gdiplus::GpPenAlignment) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetPenMode, (Gdiplus::GpPen*, Gdiplus::GpPenAlignment*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetPenTransform, (Gdiplus::GpPen*, Gdiplus::GpMatrix*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetPenTransform, (Gdiplus::GpPen*, Gdiplus::GpMatrix*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipResetPenTransform, (Gdiplus::GpPen*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipMultiplyPenTransform, (Gdiplus::GpPen*, GDIPCONST Gdiplus::GpMatrix*, Gdiplus::GpMatrixOrder) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipTranslatePenTransform, (Gdiplus::GpPen*, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::GpMatrixOrder) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipScalePenTransform, (Gdiplus::GpPen*, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::GpMatrixOrder) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipRotatePenTransform, (Gdiplus::GpPen*, Gdiplus::REAL, Gdiplus::GpMatrixOrder) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetPenColor, (Gdiplus::GpPen*, Gdiplus::ARGB) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetPenColor, (Gdiplus::GpPen*, Gdiplus::ARGB*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetPenBrushFill, (Gdiplus::GpPen*, Gdiplus::GpBrush*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetPenBrushFill, (Gdiplus::GpPen*, Gdiplus::GpBrush**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetPenFillType, (Gdiplus::GpPen*, Gdiplus::GpPenType*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetPenDashStyle, (Gdiplus::GpPen*, Gdiplus::GpDashStyle*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetPenDashStyle, (Gdiplus::GpPen*, Gdiplus::GpDashStyle) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetPenDashOffset, (Gdiplus::GpPen*, Gdiplus::REAL*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetPenDashOffset, (Gdiplus::GpPen*, Gdiplus::REAL) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetPenDashCount, (Gdiplus::GpPen*, INT*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetPenDashArray, (Gdiplus::GpPen*, GDIPCONST Gdiplus::REAL*, INT ) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetPenDashArray, (Gdiplus::GpPen*, Gdiplus::REAL*, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetPenCompoundCount, (Gdiplus::GpPen*, INT*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetPenCompoundArray, (Gdiplus::GpPen*, GDIPCONST Gdiplus::REAL*, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetPenCompoundArray, (Gdiplus::GpPen*, Gdiplus::REAL*, INT) )

// DrawLine APIs
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawLine, (Gdiplus::GpGraphics*, Gdiplus::GpPen*, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawLineI, (Gdiplus::GpGraphics*, Gdiplus::GpPen*, INT, INT, INT, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawLines, (Gdiplus::GpGraphics*, Gdiplus::GpPen*, GDIPCONST Gdiplus::GpPointF*, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawLinesI, (Gdiplus::GpGraphics*, Gdiplus::GpPen*, GDIPCONST Gdiplus::GpPoint*, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawArc, (Gdiplus::GpGraphics*, Gdiplus::GpPen*, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawArcI, (Gdiplus::GpGraphics*, Gdiplus::GpPen*, INT, INT, INT, Gdiplus::REAL, Gdiplus::REAL) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawBezier, (Gdiplus::GpGraphics*, Gdiplus::GpPen*, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawBezierI, (Gdiplus::GpGraphics*, Gdiplus::GpPen*, INT, INT, INT, INT, INT, INT, INT, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawBeziers, (Gdiplus::GpGraphics*, Gdiplus::GpPen*, GDIPCONST Gdiplus::GpPointF*, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawBeziersI, (Gdiplus::GpGraphics*, Gdiplus::GpPen*, GDIPCONST Gdiplus::GpPoint*, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawRectangle, (Gdiplus::GpGraphics*, Gdiplus::GpPen*, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawRectangleI, (Gdiplus::GpGraphics*, Gdiplus::GpPen*, INT, INT, INT, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawRectangles, (Gdiplus::GpGraphics*, Gdiplus::GpPen*, GDIPCONST Gdiplus::GpRectF*, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawRectanglesI, (Gdiplus::GpGraphics*, Gdiplus::GpPen*, GDIPCONST Gdiplus::GpRect*, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawEllipse, (Gdiplus::GpGraphics*, Gdiplus::GpPen*, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawEllipseI, (Gdiplus::GpGraphics*, Gdiplus::GpPen*, INT, INT, INT, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawPie, (Gdiplus::GpGraphics*, Gdiplus::GpPen*, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawPieI, (Gdiplus::GpGraphics*, Gdiplus::GpPen*, INT, INT, INT, INT, Gdiplus::REAL, Gdiplus::REAL) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawPolygon, (Gdiplus::GpGraphics*, Gdiplus::GpPen*, GDIPCONST Gdiplus::GpPointF*, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawPolygonI, (Gdiplus::GpGraphics*, Gdiplus::GpPen*, GDIPCONST Gdiplus::GpPoint*, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawPath, (Gdiplus::GpGraphics*, Gdiplus::GpPen*, Gdiplus::GpPath*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawCurve, (Gdiplus::GpGraphics*, Gdiplus::GpPen*, GDIPCONST Gdiplus::GpPointF*, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawCurveI, (Gdiplus::GpGraphics*, Gdiplus::GpPen*, GDIPCONST Gdiplus::GpPoint*, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawCurve2, (Gdiplus::GpGraphics*, Gdiplus::GpPen*, GDIPCONST Gdiplus::GpPointF*, INT, Gdiplus::REAL) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawCurve2I, (Gdiplus::GpGraphics*, Gdiplus::GpPen*, GDIPCONST Gdiplus::GpPoint*, INT, Gdiplus::REAL) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawCurve3, (Gdiplus::GpGraphics*, Gdiplus::GpPen*, GDIPCONST Gdiplus::GpPointF*, INT, INT, INT, Gdiplus::REAL) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawCurve3I, (Gdiplus::GpGraphics*, Gdiplus::GpPen*, GDIPCONST Gdiplus::GpPoint*, INT, INT, INT, Gdiplus::REAL) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawClosedCurve, (Gdiplus::GpGraphics*, Gdiplus::GpPen*, GDIPCONST Gdiplus::GpPointF*, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawClosedCurveI, (Gdiplus::GpGraphics*, Gdiplus::GpPen*, GDIPCONST Gdiplus::GpPoint*, INT ) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawClosedCurve2, (Gdiplus::GpGraphics*, Gdiplus::GpPen*, GDIPCONST Gdiplus::GpPointF*, INT, Gdiplus::REAL) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawClosedCurve2I, (Gdiplus::GpGraphics*, Gdiplus::GpPen*, GDIPCONST Gdiplus::GpPoint*, INT, Gdiplus::REAL) )

// Fill APIs
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGraphicsClear, (Gdiplus::GpGraphics*, Gdiplus::ARGB) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipFillRectangle, (Gdiplus::GpGraphics*, Gdiplus::GpBrush*, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipFillRectangleI, (Gdiplus::GpGraphics*, Gdiplus::GpBrush*, INT, INT, INT, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipFillRectangles, (Gdiplus::GpGraphics*, Gdiplus::GpBrush*, GDIPCONST Gdiplus::GpRectF*, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipFillRectanglesI, (Gdiplus::GpGraphics*, Gdiplus::GpBrush*, GDIPCONST Gdiplus::GpRect*, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipFillPolygon, (Gdiplus::GpGraphics*, Gdiplus::GpBrush*, GDIPCONST Gdiplus::GpPointF*, INT, Gdiplus::GpFillMode) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipFillPolygonI, (Gdiplus::GpGraphics*, Gdiplus::GpBrush*, GDIPCONST Gdiplus::GpPoint*, INT, Gdiplus::GpFillMode) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipFillPolygon2, (Gdiplus::GpGraphics*, Gdiplus::GpBrush*, GDIPCONST Gdiplus::GpPointF*, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipFillPolygon2I, (Gdiplus::GpGraphics*, Gdiplus::GpBrush*, GDIPCONST Gdiplus::GpPoint*, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipFillEllipse, (Gdiplus::GpGraphics*, Gdiplus::GpBrush*, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipFillEllipseI, (Gdiplus::GpGraphics*, Gdiplus::GpBrush*, INT, INT, INT, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipFillPie, (Gdiplus::GpGraphics*, Gdiplus::GpBrush*, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipFillPieI, (Gdiplus::GpGraphics*, Gdiplus::GpBrush*, INT, INT, INT, INT, Gdiplus::REAL, Gdiplus::REAL) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipFillPath, (Gdiplus::GpGraphics*, Gdiplus::GpBrush*, Gdiplus::GpPath*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipFillClosedCurve, (Gdiplus::GpGraphics*, Gdiplus::GpBrush*, GDIPCONST Gdiplus::GpPointF*, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipFillClosedCurveI, (Gdiplus::GpGraphics*, Gdiplus::GpBrush*, GDIPCONST Gdiplus::GpPoint*, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipFillClosedCurve2, (Gdiplus::GpGraphics*, Gdiplus::GpBrush*, GDIPCONST Gdiplus::GpPointF*, INT, Gdiplus::REAL, Gdiplus::GpFillMode) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipFillClosedCurve2I, (Gdiplus::GpGraphics*, Gdiplus::GpBrush*, GDIPCONST Gdiplus::GpPoint*, INT, Gdiplus::REAL, Gdiplus::GpFillMode) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipFillRegion, (Gdiplus::GpGraphics*, Gdiplus::GpBrush*, Gdiplus::GpRegion*) )

// DrawImage APIs
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawImage, (Gdiplus::GpGraphics*, Gdiplus::GpImage*, Gdiplus::REAL, Gdiplus::REAL) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawImageI, (Gdiplus::GpGraphics*, Gdiplus::GpImage*, INT, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawImageRect, (Gdiplus::GpGraphics*, Gdiplus::GpImage*, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawImageRectI, (Gdiplus::GpGraphics*, Gdiplus::GpImage*, INT, INT, INT, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawImagePoints, (Gdiplus::GpGraphics*, Gdiplus::GpImage*, GDIPCONST Gdiplus::GpPointF*, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawImagePointsI, (Gdiplus::GpGraphics*, Gdiplus::GpImage*, GDIPCONST Gdiplus::GpPoint*, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawImagePointRect, (Gdiplus::GpGraphics*, Gdiplus::GpImage*, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::GpUnit) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawImagePointRectI, (Gdiplus::GpGraphics*, Gdiplus::GpImage*, INT, INT, INT, INT, INT, INT, Gdiplus::GpUnit) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawImageRectRect, (Gdiplus::GpGraphics*, Gdiplus::GpImage*, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::GpUnit, GDIPCONST Gdiplus::GpImageAttributes*, Gdiplus::DrawImageAbort, VOID*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawImageRectRectI, (Gdiplus::GpGraphics*, Gdiplus::GpImage*, INT, INT, INT, INT, INT, INT, INT, INT, Gdiplus::GpUnit, GDIPCONST Gdiplus::GpImageAttributes*, Gdiplus::DrawImageAbort, VOID*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawImagePointsRect, (Gdiplus::GpGraphics*, Gdiplus::GpImage*, GDIPCONST Gdiplus::GpPointF*, INT, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::GpUnit, GDIPCONST Gdiplus::GpImageAttributes*, Gdiplus::DrawImageAbort, VOID*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawImagePointsRectI, (Gdiplus::GpGraphics*, Gdiplus::GpImage*, GDIPCONST Gdiplus::GpPoint*, INT, INT, INT, INT, INT, Gdiplus::GpUnit, GDIPCONST Gdiplus::GpImageAttributes*, Gdiplus::DrawImageAbort, VOID*) )

// Clip APIs
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetClipGraphics, (Gdiplus::GpGraphics*, Gdiplus::GpGraphics*, Gdiplus::CombineMode) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetClipRect, (Gdiplus::GpGraphics*, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::REAL, Gdiplus::CombineMode) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetClipRectI, (Gdiplus::GpGraphics*, INT, INT, INT, INT, Gdiplus::CombineMode) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetClipPath, (Gdiplus::GpGraphics*, Gdiplus::GpPath*, Gdiplus::CombineMode) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetClipRegion, (Gdiplus::GpGraphics*, Gdiplus::GpRegion*, Gdiplus::CombineMode) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetClipHrgn, (Gdiplus::GpGraphics*, HRGN, Gdiplus::CombineMode) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipResetClip, (Gdiplus::GpGraphics*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipTranslateClip, (Gdiplus::GpGraphics*, Gdiplus::REAL, Gdiplus::REAL) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipTranslateClipI, (Gdiplus::GpGraphics*, INT, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetClip, (Gdiplus::GpGraphics*, Gdiplus::GpRegion*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetClipBounds, (Gdiplus::GpGraphics*, Gdiplus::GpRectF*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetClipBoundsI, (Gdiplus::GpGraphics*, Gdiplus::GpRect*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipIsClipEmpty, (Gdiplus::GpGraphics*, BOOL*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetVisibleClipBounds, (Gdiplus::GpGraphics*, Gdiplus::GpRectF*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetVisibleClipBoundsI, (Gdiplus::GpGraphics*, Gdiplus::GpRect*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipIsVisibleClipEmpty, (Gdiplus::GpGraphics*, BOOL*) )

// Image Decoder/Encoder APIs
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetImageDecodersSize, (UINT*, UINT*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetImageDecoders, (UINT, UINT, Gdiplus::ImageCodecInfo*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetImageEncodersSize, (UINT*, UINT*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetImageEncoders, (UINT, UINT, Gdiplus::ImageCodecInfo*) )

// FontFamily APIs
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateFontFamilyFromName, (GDIPCONST WCHAR*, Gdiplus::GpFontCollection*, Gdiplus::GpFontFamily**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDeleteFontFamily, (Gdiplus::GpFontFamily*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCloneFontFamily, (Gdiplus::GpFontFamily*, Gdiplus::GpFontFamily**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetGenericFontFamilySansSerif, (Gdiplus::GpFontFamily**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetGenericFontFamilySerif, (Gdiplus::GpFontFamily**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetGenericFontFamilyMonospace, (Gdiplus::GpFontFamily**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetFamilyName, (GDIPCONST Gdiplus::GpFontFamily*, LPWSTR, LANGID) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipIsStyleAvailable, (GDIPCONST Gdiplus::GpFontFamily*, INT, BOOL*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipFontCollectionEnumerable, (Gdiplus::GpFontCollection*, Gdiplus::GpGraphics*, INT*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipFontCollectionEnumerate, (Gdiplus::GpFontCollection*, INT, Gdiplus::GpFontFamily*[], INT*, Gdiplus::GpGraphics*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetEmHeight, (GDIPCONST Gdiplus::GpFontFamily*, INT, UINT16*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetCellAscent, (GDIPCONST Gdiplus::GpFontFamily*, INT, UINT16*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetCellDescent, (GDIPCONST Gdiplus::GpFontFamily*, INT, UINT16*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetLineSpacing, (GDIPCONST Gdiplus::GpFontFamily*, INT, UINT16*) )

// Font APIs
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateFontFromDC, (HDC, Gdiplus::GpFont**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateFontFromLogfontA, (HDC, GDIPCONST LOGFONTA*, Gdiplus::GpFont**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateFontFromLogfontW, (HDC, GDIPCONST LOGFONTW*, Gdiplus::GpFont**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateFont, (GDIPCONST Gdiplus::GpFontFamily*, Gdiplus::REAL, INT, Gdiplus::Unit, Gdiplus::GpFont**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCloneFont, (Gdiplus::GpFont*, Gdiplus::GpFont**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDeleteFont, (Gdiplus::GpFont*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetFamily, (Gdiplus::GpFont*, Gdiplus::GpFontFamily**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetFontStyle, (Gdiplus::GpFont*, INT*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetFontSize, (Gdiplus::GpFont*, Gdiplus::REAL*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetFontUnit, (Gdiplus::GpFont*, Gdiplus::Unit*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetFontHeight, (GDIPCONST Gdiplus::GpFont*, GDIPCONST Gdiplus::GpGraphics*, Gdiplus::REAL*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetFontHeightGivenDPI, (GDIPCONST Gdiplus::GpFont*, Gdiplus::REAL, Gdiplus::REAL*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetLogFontA, (Gdiplus::GpFont*, Gdiplus::GpGraphics*, LOGFONTA*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetLogFontW, (Gdiplus::GpFont*, Gdiplus::GpGraphics*, LOGFONTW*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipNewInstalledFontCollection, (Gdiplus::GpFontCollection**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipNewPrivateFontCollection, (Gdiplus::GpFontCollection**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDeletePrivateFontCollection, (Gdiplus::GpFontCollection**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetFontCollectionFamilyCount, (Gdiplus::GpFontCollection*, INT*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetFontCollectionFamilyList, (Gdiplus::GpFontCollection*, INT, Gdiplus::GpFontFamily*[], INT*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipPrivateAddFontFile, (Gdiplus::GpFontCollection*, GDIPCONST WCHAR*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipPrivateAddMemoryFont, (Gdiplus::GpFontCollection*, GDIPCONST void*, INT) )

// Text APIs
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawString, (Gdiplus::GpGraphics*, GDIPCONST WCHAR*, INT, GDIPCONST Gdiplus::GpFont*, GDIPCONST Gdiplus::RectF*, GDIPCONST Gdiplus::GpStringFormat*, GDIPCONST Gdiplus::GpBrush*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipMeasureString, (Gdiplus::GpGraphics*, GDIPCONST WCHAR*, INT, GDIPCONST Gdiplus::GpFont*, GDIPCONST Gdiplus::RectF*,GDIPCONST Gdiplus::GpStringFormat*, Gdiplus::RectF*, INT*, INT*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipMeasureCharacterRanges, (Gdiplus::GpGraphics*, GDIPCONST WCHAR*, INT, GDIPCONST Gdiplus::GpFont*, GDIPCONST Gdiplus::RectF&, GDIPCONST Gdiplus::GpStringFormat*, INT, Gdiplus::GpRegion**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawDriverString, (Gdiplus::GpGraphics*, GDIPCONST UINT16*, INT, GDIPCONST Gdiplus::GpFont*, GDIPCONST Gdiplus::GpBrush*, GDIPCONST Gdiplus::PointF*, INT, GDIPCONST Gdiplus::GpMatrix*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipMeasureDriverString, (Gdiplus::GpGraphics*, GDIPCONST UINT16*, INT, GDIPCONST Gdiplus::GpFont*, GDIPCONST Gdiplus::PointF*, INT, GDIPCONST Gdiplus::GpMatrix*, Gdiplus::RectF*) )

// String format APIs
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateStringFormat, (INT, LANGID, Gdiplus::GpStringFormat**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipStringFormatGetGenericDefault, (Gdiplus::GpStringFormat**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipStringFormatGetGenericTypographic, (Gdiplus::GpStringFormat**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDeleteStringFormat, (Gdiplus::GpStringFormat*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCloneStringFormat, (GDIPCONST Gdiplus::GpStringFormat*, Gdiplus::GpStringFormat**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetStringFormatFlags, (Gdiplus::GpStringFormat*, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetStringFormatFlags, (GDIPCONST Gdiplus::GpStringFormat*, INT*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetStringFormatAlign, (Gdiplus::GpStringFormat*, Gdiplus::StringAlignment) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetStringFormatAlign, (GDIPCONST Gdiplus::GpStringFormat*, Gdiplus::StringAlignment*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetStringFormatLineAlign, (Gdiplus::GpStringFormat*, Gdiplus::StringAlignment) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetStringFormatLineAlign, (GDIPCONST Gdiplus::GpStringFormat*, Gdiplus::StringAlignment*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetStringFormatTrimming, (Gdiplus::GpStringFormat*, Gdiplus::StringTrimming) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetStringFormatTrimming, (GDIPCONST Gdiplus::GpStringFormat*, Gdiplus::StringTrimming*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetStringFormatHotkeyPrefix, (Gdiplus::GpStringFormat*, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetStringFormatHotkeyPrefix, (GDIPCONST Gdiplus::GpStringFormat*, INT*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetStringFormatTabStops, (Gdiplus::GpStringFormat*, Gdiplus::REAL, INT, GDIPCONST Gdiplus::REAL*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetStringFormatTabStops, (GDIPCONST Gdiplus::GpStringFormat*, INT, Gdiplus::REAL*, Gdiplus::REAL*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetStringFormatTabStopCount, (GDIPCONST Gdiplus::GpStringFormat*, INT*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetStringFormatDigitSubstitution, (Gdiplus::GpStringFormat*, LANGID, Gdiplus::StringDigitSubstitute) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetStringFormatDigitSubstitution, (GDIPCONST Gdiplus::GpStringFormat*, LANGID*, Gdiplus::StringDigitSubstitute*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipGetStringFormatMeasurableCharacterRangeCount, (GDIPCONST Gdiplus::GpStringFormat*, INT*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetStringFormatMeasurableCharacterRanges, (Gdiplus::GpStringFormat*, INT, GDIPCONST Gdiplus::CharacterRange*) )

// Cached Bitmap APIs
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipCreateCachedBitmap, (Gdiplus::GpBitmap*, Gdiplus::GpGraphics*, Gdiplus::GpCachedBitmap**) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDeleteCachedBitmap, (Gdiplus::GpCachedBitmap*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipDrawCachedBitmap, (Gdiplus::GpGraphics*, Gdiplus::GpCachedBitmap*, INT, INT) )
DEFINE_FUNC_PTR( UINT,				GdipEmfToWmfBits, (HENHMETAFILE, UINT, LPBYTE, INT, INT) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipSetImageAttributesCachedBackground, (Gdiplus::GpImageAttributes*, BOOL) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdipTestControl, (Gdiplus::GpTestControlEnum, void*) )
DEFINE_FUNC_PTR( Gdiplus::GpStatus,	GdiplusNotificationHook, (ULONG_PTR*) )
DEFINE_FUNC_PTR( VOID,				GdiplusNotificationUnhook, (ULONG_PTR) )